Threshold = 95
DisplayMonitorSources = true
EnableUpdates = true
GuiltTripped = true
FilterInput = true
FilterOutput = true
LastUsedInput = "alsa_output.pci-0000_00_1f.3.analog-stereo.monitor"
LastUsedOutput = "alsa_output.pci-0000_00_1f.3.analog-stereo"
